# Generated by Django 5.0.6 on 2026-08-01 08:27

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0003_sourcingsettings_reseller_min_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. JazzCash, EasyPaisa, Meezan Bank.', max_length=100)),
                ('account_title', models.CharField(help_text='Account holder name.', max_length=150)),
                ('account_number', models.CharField(help_text='Account / wallet number or IBAN.', max_length=64)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
                ('instructions', models.TextField(blank=True, default='', help_text="Shown to the customer, e.g. 'Send exact amount, then enter TID'.")),
                ('sender_ids', models.CharField(blank=True, default='', help_text="Comma-separated SMS senders to auto-match, e.g. '8558,JazzCash'.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField()),
                ('sender', models.CharField(blank=True, default='', max_length=64)),
                ('trx_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sms', to='sourcing.order')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Incoming SMS',
                'verbose_name_plural': 'Incoming SMS',
                'ordering': ['-received_at'],
            },
        ),
    ]
