# Generated by Django 6.0 on 2025-12-31 05:19

import cloudinary.models
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productplan',
            name='duration_months',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productplan',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='whatsapp_number',
            field=models.CharField(help_text='Format: +92XXXXXXXXXX', max_length=13, validators=[product.models.validate_pk_whatsapp]),
        ),
    ]
