# Generated by Django 6.0 on 2026-01-04 13:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
