# Generated by Django 5.0.6 on 2026-08-01 08:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sourcing', '0003_sourcingsettings_reseller_min_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Reseller's own money. Spendable on purchases. Not our income.", max_digits=14)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_required', models.BooleanField(default=True, help_text='If off, this reseller can operate without the minimum deposit.')),
                ('wallet_required', models.BooleanField(default=True, help_text='If off, this reseller may pay per order (SMS) instead of wallet.')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller',
                'verbose_name_plural': 'Resellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Admin adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, negative = debit.', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='sourcing.order')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reseller.reseller')),
                ('sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.incomingsms')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
