# Generated by Django 5.0.6 on 2026-08-01 07:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_own_stock', models.BooleanField(default=True, help_text='If own stock exists, deliver from it before hitting bots.')),
                ('usd_to_pkr_rate', models.DecimalField(decimal_places=4, default=Decimal('280.0000'), help_text="Used to convert a bot's USD cost into a PKR selling price.", max_digits=12)),
                ('default_retail_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Default markup for normal (retail) customers.', max_digits=6)),
                ('default_reseller_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default markup for reseller-panel customers.', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sourcing Settings',
                'verbose_name_plural': 'Sourcing Settings',
            },
        ),
        migrations.CreateModel(
            name='SupplierBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Label to recognise this bot, e.g. 'Telegram Primary'.", max_length=100)),
                ('bot_source', models.CharField(choices=[('primary', 'Telegram (primary)'), ('telegram2', 'Telegram (2nd)'), ('binance', 'Binance bot'), ('bybit', 'Bybit bot'), ('other', 'Other')], default='other', help_text='Informational only; the key itself decides the real flow.', max_length=20)),
                ('api_key', models.CharField(help_text='Canboso buyer key (tgb_...). Kept server-side only.', max_length=255)),
                ('base_url', models.CharField(default='https://canboso.com', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to exclude this bot from price comparison / purchases.')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Tie-breaker when two bots have the same price. Lower = preferred.')),
                ('wallet_currency', models.CharField(blank=True, default='', max_length=8)),
                ('last_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('last_balance_text', models.CharField(blank=True, default='', max_length=64)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier Bot',
                'verbose_name_plural': 'Supplier Bots',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(help_text='Prevents the same checkout from creating duplicate orders.', max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('buyer_type', models.CharField(choices=[('retail', 'Retail'), ('reseller', 'Reseller')], default='retail', max_length=10)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('slot_months', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed (no stock / all bots failed)'), ('needs_review', 'Needs review (ambiguous)')], default='pending', max_length=16)),
                ('source', models.CharField(blank=True, choices=[('own_stock', 'Own stock'), ('bot', 'Bot'), ('', '—')], default='', max_length=10)),
                ('sell_amount_pkr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cost_currency', models.CharField(blank=True, default='', max_length=8)),
                ('canboso_order_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sourcing_orders', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_orders', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sourcing.supplierbot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveredAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('verify_email', models.CharField(blank=True, default='', max_length=255)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_accounts', to='sourcing.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_match_enabled', models.BooleanField(default=True, help_text='Let the system auto-link bot products by name. Manual links always take priority and are never overwritten.')),
                ('retail_margin_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = use global default retail margin.', max_digits=6, null=True)),
                ('reseller_margin_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = use global default reseller margin.', max_digits=6, null=True)),
                ('retail_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed retail price in PKR (ignores margin/cost).', max_digits=12, null=True)),
                ('reseller_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed reseller price in PKR (ignores margin/cost).', max_digits=12, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Sourcing',
                'verbose_name_plural': 'Product Sourcing',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('verify_email', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.TextField(blank=True, default='')),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Stock Item (own)',
                'verbose_name_plural': 'Stock Items (own)',
                'ordering': ['is_sold', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(help_text="Canboso product _id (or 'slot_chatgpt_business').", max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_raw', models.CharField(blank=True, default='', max_length=255)),
                ('wallet_currency', models.CharField(blank=True, default='', max_length=8)),
                ('wallet_pricing', models.DecimalField(blank=True, decimal_places=6, help_text="Price in the bot's wallet currency.", max_digits=18, null=True)),
                ('usd_pricing', models.DecimalField(blank=True, decimal_places=6, help_text='Price in USD — used to compare across bots.', max_digits=18, null=True)),
                ('available', models.IntegerField(blank=True, help_text='Stock available on this bot (null = unknown / unlimited).', null=True)),
                ('is_slot', models.BooleanField(default=False)),
                ('slot_durations', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Full product object as returned by Canboso.')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sourcing.supplierbot')),
            ],
            options={
                'verbose_name': 'Supplier Product',
                'verbose_name_plural': 'Supplier Products',
                'ordering': ['name', 'usd_pricing'],
                'unique_together': {('bot', 'remote_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('auto', 'Auto (by name)'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('buy_quantity', models.PositiveIntegerField(default=1, help_text='Units to buy per 1 unit sold (normal products). Slots ignore this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_sourcing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sourcing.productsourcing')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sourcing.supplierproduct')),
            ],
            options={
                'verbose_name': 'Product ↔ Bot link',
                'verbose_name_plural': 'Product ↔ Bot links',
                'unique_together': {('product_sourcing', 'supplier_product')},
            },
        ),
    ]
