# Generated by Django 5.0.6 on 2026-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsourcing',
            name='show_on_reseller',
            field=models.BooleanField(default=False, help_text='Show this product on the reseller panel (login required).'),
        ),
        migrations.AddField(
            model_name='productsourcing',
            name='show_on_retail',
            field=models.BooleanField(default=False, help_text='Show this product on the public (retail) store.'),
        ),
    ]
