# Generated by Django 5.0.6 on 2026-08-01 08:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_productsourcing_show_on_reseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingsettings',
            name='reseller_min_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Minimum wallet deposit a reseller needs to activate the panel.', max_digits=12),
        ),
    ]
