# Generated by Django 5.0.6 on 2026-08-01 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0003_sourcingsettings_reseller_min_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productsourcelink',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Shown to the customer (bot name is hidden). Blank = 'Plan N'.", max_length=100),
        ),
        migrations.AddField(
            model_name='productsourcing',
            name='reseller_commission_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra flat PKR added to every reseller offer (on top of %).', max_digits=12),
        ),
        migrations.AddField(
            model_name='productsourcing',
            name='retail_commission_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra flat PKR added to every retail offer (on top of %).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='productsourcing',
            name='reseller_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy, unused.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productsourcing',
            name='retail_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy, unused.', max_digits=12, null=True),
        ),
    ]
