# Generated by Django 5.0.6 on 2026-08-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0004_order_offer_label_productsourcelink_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StockField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Email, Password, 2FA', max_length=100)),
                ('value', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sourcing.stockitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
