# Generated by Django 5.0.6 on 2026-08-01 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_notes'),
        ('sourcing', '0005_alter_stockitem_password_alter_stockitem_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveredaccount',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deliveredaccount',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StockOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text="Shown to the customer, e.g. '1 Month (in-house)'.", max_length=100)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reseller_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('show_on_retail', models.BooleanField(default=True)),
                ('show_on_reseller', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_offers', to='product.product')),
            ],
            options={
                'verbose_name': 'Own-stock Offer',
                'verbose_name_plural': 'Own-stock Offers',
            },
        ),
    ]
