# Generated by Django 5.0.6 on 2026-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0006_deliveredaccount_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsourcelink',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Optional. Shown (collapsed) under the offer title on the site.'),
        ),
        migrations.AddField(
            model_name='stockoffer',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Optional. Shown (collapsed) under the offer title on the site.'),
        ),
    ]
